CRUD/Models/CrudContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRUD.Models;

public partial class CrudContext : DbContext
{
    public CrudContext()
    {
    }

    public CrudContext(DbContextOptions<CrudContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ProductList> ProductLists { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("name=conn");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ProductList>(entity =>
        {
            entity.HasKey(e => e.Pid).HasName("PK__ProductL__C5775520DDDED0B2");

            entity.ToTable("ProductList");

            entity.Property(e => e.Pid).HasColumnName("PID");
            entity.Property(e => e.Quantity).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.Rate).HasColumnType("decimal(12, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

CRUD/Models/ErrorViewModel.cs
namespace CRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD/Models/ProductList.cs
using System;
using System.Collections.Generic;

namespace CRUD.Models;

public partial class ProductList
{
    public int Pid { get; set; }

    public string ProductName { get; set; } = null!;

    public string ProductDescription { get; set; } = null!;

    public string ProductFile { get; set; } = null!;

    public decimal Quantity { get; set; }

    public decimal Rate { get; set; }
}

CRUD/Controllers/CRUDController.cs
using CRUD.Models;
using Microsoft.AspNetCore.Mvc;

namespace CRUD.Controllers
{
    public class CRUDController : Controller
    {
        private readonly CrudContext _context;
        public CRUDController(CrudContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Display()
        {
            List <ProductList> products = new List<ProductList>();
            products=_context.ProductLists.ToList();
            return View(products);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task <IActionResult> Create(ProductList model)
        {
            if(model != null)
            {
                _context.ProductLists.Add(model);
                
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Display");
        }
    }
}

CRUD/Controllers/HomeController.cs
using CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD/Views/CRUD/Create.cshtml
@model CRUD.Models.ProductList
@{
    ViewData["Title"] = "Create";
}
<div class="card">
    <form asp-controller="CRUD" asp-action="Create" method="post">
    <h1 class="card-header bg-black text-light d-block">Create Product</h1>
        <div class="card-body">
            <div class="">
                    <label asp-for="ProductName">Product Name:</label>
                <input class="form-control" autocomplete="off" placeholder="Enter Product Name" asp-for="ProductName" />
                    <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="">
                <label asp-for="ProductDescription">Product Description:</label>
                <input class="form-control" autocomplete="off" asp-for="ProductDescription" placeholder="Enter Product Description" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <label asp-for="ProductFile">
                        Product Image:
                    </label>
                    <input class="form-control" autocomplete="off" placeholder="Enter product Image" asp-for="ProductFile" />
                    <span asp-validation-for="ProductFile" class="text-danger"></span>
                </div>
                <div class="col-md-4">
                    <label asp-for="Quantity">
                        Quanitity:
                    </label>
                    <input class="form-control" autocomplete="off" placeholder="Enter Quantity" asp-for="Quantity" />
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
                    <div class="col-md-4">
                        <label asp-for="Rate">
                            Rate:
                        </label>
                        <input class="form-control" autocomplete="off" placeholder="Enter Rate" asp-for="Rate" />
                        <span asp-validation-for="Rate" class="text-danger"></span>
                    </div>
        </div>

        <input type="submit" class="btn btn-dark py-2 my-2" />
        </div>
    </form>
</div>

CRUD/Views/CRUD/Display.cshtml
@model List<ProductList>
@{
    ViewData["Title"] = "Display";
    int count = 0;
}
 
@if (Model.Count>0){
    <table class="table">
        <thead>
        <tr>
            <th scope="col">S No.</th>
            <th scope="col">ProductName</th>
            <th scope="col">ProductDescription</th>
            <th scope="col">ProductImage</th>
            <th scope="col">Quantity</th>
            <th scope="col">Rate</th>
        </tr>
        </thead>
            <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td>@(count=count+1)</td>
                    <td>@product.ProductName</td>
                    <td>@product.ProductDescription</td>
                    <td><img src="@product.ProductFile" class="img-thumbnail" /></td>
                    <td>@product.Quantity</td>
                    <td>@product.Rate</td>
                </tr>
            }

    </tbody>
</table>
    }
    else
    {
        <h1 class="text-center text-danger">No Items</h1>
    }

CRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CRUD" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CRUD" asp-action="Display">Display</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>